# Generated by Django 6.0.1 on 2026-07-08 16:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkedUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.CharField(max_length=100, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.BigIntegerField()),
                ('chunk_size', models.IntegerField()),
                ('total_chunks', models.IntegerField()),
                ('uploaded_chunks', models.IntegerField(default=0)),
                ('chat_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppMedia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Media name', max_length=255)),
                ('size', models.FloatField(help_text='Media size')),
                ('type', models.CharField(help_text='Media type and format (e.g., image/jpeg)', max_length=100)),
                ('duration', models.FloatField(blank=True, help_text='Media duration', null=True)),
                ('thumbnail', models.TextField(blank=True, help_text='Base64 thumnail', null=True)),
                ('path', models.TextField()),
                ('preview', models.TextField(blank=True, help_text='Base64 preview or URL', null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('contact_phones', models.TextField(blank=True, null=True)),
                ('contact_emails', models.TextField(blank=True, null=True)),
                ('contact_org', models.TextField(blank=True, null=True)),
                ('contact_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Media',
                'verbose_name_plural': 'WhatsApp Media',
                'db_table': 'whatsapp_media',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.IntegerField()),
                ('user', models.IntegerField()),
                ('emoji', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_verification_tokens',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_reset_tokens',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppAdminUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text="Internal name for this connection (e.g., 'Sales Team Number')", max_length=255, null=True)),
                ('access_token', models.CharField(blank=True, help_text='System User Access Token from Meta Developer Portal', max_length=500, null=True)),
                ('templates_access_token', models.CharField(blank=True, help_text='Template access token', max_length=500, null=True)),
                ('phone_number_id', models.CharField(blank=True, help_text='The specific Phone Number ID sending the messages', max_length=100, null=True)),
                ('waba_id', models.CharField(blank=True, help_text='WhatsApp Business Account ID (Optional, good for templates)', max_length=100)),
                ('app_id', models.CharField(blank=True, help_text='WhatsApp APP Account ID', max_length=100)),
                ('message_base_version', models.CharField(default='v17.0', help_text='WhatsApp messages base version', max_length=10)),
                ('templates_base_version', models.CharField(default='v18.0', help_text='WhatsApp templates base version', max_length=10)),
                ('oauth_base_version', models.CharField(default='v19.0', help_text='WhatsApp oauth base version', max_length=10)),
                ('app_secret', models.CharField(blank=True, help_text='WhatsApp Business App secret', max_length=100)),
                ('webhook_verify_token', models.CharField(default=uuid.uuid4, help_text='Token used to verify incoming webhooks from Meta', max_length=100)),
                ('subscribed_fields', models.CharField(blank=True, default=True, max_length=255, null=True)),
                ('domain', models.CharField(blank=True, default=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WhatsAppAdminUser',
                'verbose_name_plural': 'WhatsAppAdminUser',
            },
        ),
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wamid', models.CharField(blank=True, max_length=255, null=True)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('userid', models.IntegerField()),
                ('sender_userid', models.IntegerField(blank=True, null=True)),
                ('wa_timestamp', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message_type', models.CharField(max_length=50)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('template', models.TextField(blank=True, null=True)),
                ('Error', models.TextField(blank=True, null=True)),
                ('language_code', models.CharField(default='en_US', max_length=10)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.JSONField(blank=True, null=True)),
                ('whatsapp_admin', models.ForeignKey(blank=True, db_column='owner_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='WhatsPanel.whatsappadminuser')),
            ],
            options={
                'db_table': 'ScheduledMessage',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wamid', models.CharField(max_length=255, unique=True)),
                ('userid', models.IntegerField()),
                ('sender_userid', models.IntegerField(blank=True, null=True)),
                ('sender_phonenumber', models.CharField(blank=True, max_length=255, null=True)),
                ('wa_timestamp', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message_type', models.CharField(max_length=50)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('reply_to_wamid', models.CharField(blank=True, max_length=255, null=True)),
                ('media_id', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('coordinates', models.CharField(blank=True, max_length=255, null=True)),
                ('template', models.TextField(blank=True, null=True)),
                ('forwarded', models.BooleanField(blank=True, null=True)),
                ('originalSenderId', models.IntegerField(blank=True, null=True)),
                ('originalTimestamp', models.DateTimeField(blank=True, null=True)),
                ('raw_webhook_payload', models.JSONField(blank=True, null=True)),
                ('is_read', models.BooleanField(blank=True, default=False, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('error_text', models.TextField(blank=True, null=True)),
                ('whatsapp_admin', models.ForeignKey(blank=True, db_column='owner_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='WhatsPanel.whatsappadminuser')),
            ],
            options={
                'db_table': 'whatsapp_messages',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(help_text="The phone number with country code, typically formatted with a leading '+'.", max_length=30)),
                ('wa_id', models.CharField(help_text="The WhatsApp ID returned by the API. Usually the phone number without the '+'.", max_length=50, unique=True)),
                ('whatsapp_name', models.CharField(blank=True, help_text='The profile name the user has set on their WhatsApp account.', max_length=255, null=True)),
                ('is_opted_in', models.BooleanField(default=False, help_text='Has the user explicitly opted in to receive proactive template messages?')),
                ('opted_in_at', models.DateTimeField(blank=True, null=True)),
                ('is_valid_whatsapp_number', models.BooleanField(default=True, help_text='Set to False if the API returns an error indicating the number is not on WhatsApp.')),
                ('last_user_message_at', models.DateTimeField(blank=True, help_text='The timestamp of the last message received from this user. Starts the 24h window.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar', models.CharField(max_length=10)),
                ('whatsapp_admin', models.ForeignKey(blank=True, db_column='owner_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='WhatsPanel.whatsappadminuser')),
            ],
            options={
                'verbose_name': 'WhatsApp User',
                'verbose_name_plural': 'WhatsApp Users',
                'ordering': ['-last_user_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(blank=True, help_text='The unique ID assigned by WhatsApp Cloud API upon creation.', max_length=255, null=True, unique=True)),
                ('name', models.CharField(help_text="The template name (e.g., 'order_confirmation'). Must be lowercase and underscores only.", max_length=512)),
                ('language', models.CharField(default='en_US', help_text="The language code (e.g., 'en_US', 'es_ES').", max_length=10)),
                ('category', models.CharField(choices=[('AUTHENTICATION', 'Authentication'), ('MARKETING', 'Marketing'), ('UTILITY', 'Utility')], default='UTILITY', max_length=20)),
                ('status', models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('PAUSED', 'Paused'), ('DISABLED', 'Disabled'), ('PENDING_DELETION', 'Pending Deletion')], default='PENDING', max_length=20, null=True)),
                ('components', models.JSONField(default=list, help_text='JSON array containing the template components as defined by the WhatsApp API.')),
                ('rejected_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('parameter_format', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('whatsapp_admin', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='WhatsPanel.whatsappadminuser')),
            ],
            options={
                'verbose_name': 'WhatsApp Template',
                'verbose_name_plural': 'WhatsApp Templates',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'language')},
            },
        ),
    ]
